In [ ]:
!pip install numpy

##1번 문제

In [ ]:
import numpy as np
arr = np.arange(1,11)
print(arr)
print('ndim: ', arr.ndim)
print(arr.shape)
print(arr.dtype)
print('size: ', arr.size)

[ 1  2  3  4  5  6  7  8  9 10]
ndim:  1
(10,)
int64
size:  10


##2번 문제

In [ ]:
import numpy as np
arr = np.arange(10,50)
print(arr.T)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np
arr = np.random.random((10,10))
min = np.min(arr)
max = np.max(arr)
print(f"최솟값 : {min}")
print(f"최댓값 : {max}")

최솟값 : 0.006543234523884722
최댓값 : 0.9993133943009177


In [ ]:
import numpy as np
arr = np.random.randint(0,9,(3,3))
print(arr)

[[6 7 1]
 [3 2 6]
 [1 2 5]]


In [ ]:
import numpy as np
arr = np.arange(1,25)
print(arr.reshape(4,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [ ]:
import numpy as np
arr = np.arange(1,25).reshape(4,6)
result = arr[1:3, 0:4] #2행부터 3행,
print(result)

[[ 7  8  9 10]
 [13 14 15 16]]


In [ ]:
import numpy as np
arr = np.arange(1,25).reshape(4,6)
result = arr[2:4, :: -1]
print(result)

[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]


In [ ]:
import numpy as np
arr = np.arange(1,25).reshape(4,6)
print(arr[arr%2==0])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [ ]:
import numpy as np
arr = np.arange(1,25).reshape(4,6)
print(arr[(arr>=10) & (arr<=20)])

[10 11 12 13 14 15 16 17 18 19 20]


##3번 문제

In [ ]:
import numpy as np
arr = np.arange(1,21)
print('마지막 원소 : ', arr[-1])
print('모든 원소의 합 : ', arr.sum())
print('모든 원소의 평균 : ', arr.sum()/arr.size)

마지막 원소 :  20
모든 원소의 합 :  210
모든 원소의 평균 :  10.5


In [ ]:
import numpy as np
num = np.random.randint(1,31)
while True:
  user_input = int(input("숫자 입력 (종료 0 ): "))
  if user_input ==num:
    print("정답!!")
    break
  elif user_input>=num:     #python에는 else if 대신 elif
    print("더 낮은 숫자 입력!")
    continue
  elif user_input <= num:
    print("더 높은 숫자 입력!")
    continue
  elif user_input == 0:
    break
    # 1~30이 아닌 숫자 입력햇을때 try except 문으로 해주기 (python은 try catch문이 아니라 except라고 함)

숫자 입력 (종료 0 ): 10
더 높은 숫자 입력!
숫자 입력 (종료 0 ): 20
더 낮은 숫자 입력!
숫자 입력 (종료 0 ): 25
더 낮은 숫자 입력!
숫자 입력 (종료 0 ): 15
더 높은 숫자 입력!
숫자 입력 (종료 0 ): 17
더 낮은 숫자 입력!
숫자 입력 (종료 0 ): 16
정답!!


##4번 문제

In [ ]:
import numpy as np
salary = [200,150,180,220,250]
new_salary=np.array(salary,dtype = 'float64')*1.5
print('인상된 금액 : ',new_salary)
avg_salary = new_salary.sum()/new_salary.size
print('평균 금액 : ',avg_salary)
result = np.array(new_salary>=avg_salary)
print('평균 이상인 원소 : ', new_salary[result])
print('평균 이상인 원소의 개수 : ', new_salary[result].size) #result는 true, false의 값을 가지고 있음. 즉 요소가 5개임. 그러므로 result.size하면 안됨

인상된 금액 :  [300. 225. 270. 330. 375.]
평균 금액 :  300.0
평균 이상인 원소 :  [300. 330. 375.]
평균 이상인 원소의 개수 :  3
