In [ ]:
pip install pandas

In [ ]:
import pandas as pd

In [ ]:
score=pd.Series([90,44,43,23,14])
score

0    90
1    44
2    43
3    23
4    14
dtype: int64

In [ ]:
s=pd.Series([4,3.5,4.5,6,7.88])
s

0    4.00
1    3.50
2    4.50
3    6.00
4    7.88
dtype: float64

In [ ]:
s=pd.Series([90,87,45],index=['A','B','C'])
s

A    90
B    87
C    45
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
arr=np.arange(15).reshape(5,3)
print(arr)
print()
df=pd.DataFrame(arr)
print(df)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

    0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14


In [ ]:
df=pd.DataFrame({'name':['Kim','Oh','Yang'],
                 'score':[99,89,99],
                 'dept':['com','eng','math']})
df

name  score  dept
0   Kim     99   com
1    Oh     89   eng
2  Yang     99  math

In [ ]:
df=pd.read_csv('/content/sample_data/mobile.csv',index_col=0)
df

Color  price
Brand                 
Samsung   Black    100
LG         Gold     70
Apple    Silver    150
Apple      Gray    120

In [ ]:
df=pd.read_csv('/content/sample_data/mobile.csv')
df

Brand   Color  price
0  Samsung   Black    100
1       LG    Gold     70
2    Apple  Silver    150
3    Apple    Gray    120

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/weather.csv')
df

date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [ ]:
df.shape


(3653, 4)

In [ ]:
print()
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3653 entries, 0 to 3652
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   date       3653 non-null   object 
 1   temp       3653 non-null   float64
 2   max_wind   3649 non-null   float64
 3   mean_wind  3647 non-null   float64
dtypes: float64(3), object(1)
memory usage: 114.3+ KB


In [ ]:
df.head()

date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [ ]:
df.tail(8)

date  temp  max_wind  mean_wind
3645  2020-07-24  20.4       7.2        2.8
3646  2020-07-25  20.7       3.8        1.1
3647  2020-07-26  21.4       4.8        2.8
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

In [ ]:
df.index

RangeIndex(start=0, stop=3653, step=1)

In [ ]:
df.columns

Index(['date', 'temp', 'max_wind', 'mean_wind'], dtype='object')

In [ ]:
df.describe()

temp     max_wind    mean_wind
count  3653.000000  3649.000000  3647.000000
mean     12.942102     7.911099     3.936441
std       8.538507     3.029862     1.888473
min      -9.000000     2.000000     0.200000
25%       5.400000     5.700000     2.500000
50%      13.800000     7.600000     3.600000
75%      20.100000     9.700000     5.000000
max      31.300000    26.000000    14.900000

In [ ]:
df['temp'].mean()

12.942102381604162

In [ ]:
df.sort_values(by='max_wind')

date  temp  max_wind  mean_wind
1514  2014-09-23  20.7       2.0        1.0
1134  2013-09-08  20.4       2.1        0.8
421   2011-09-26  18.7       2.1        0.3
1512  2014-09-21  20.4       2.2        1.2
1005  2013-05-02   7.1       2.2        0.8
...          ...   ...       ...        ...
2988  2018-10-06  19.4      26.0        7.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

In [ ]:
df.sort_values(by='max_wind', ascending=False)

date  temp  max_wind  mean_wind
2988  2018-10-06  19.4      26.0        7.0
3340  2019-09-23  15.0      25.8       11.0
1850  2015-08-25  20.1      25.3       14.9
3339  2019-09-22  15.7      23.1       11.9
1851  2015-08-26  17.4      22.6        8.1
...          ...   ...       ...        ...
1514  2014-09-23  20.7       2.0        1.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

In [ ]:
bank=pd.read_csv('/content/sample_data/bank.csv')
bank['job'].value_counts()
bank['job'].value_counts(ascending=True)

job
student           153
housemaid         208
unemployed        223
entrepreneur      239
self-employed     256
retired           351
services          661
admin.            834
technician       1206
blue-collar      1499
management       1560
Name: count, dtype: int64

In [ ]:
bank.columns

Index(['job', 'education', 'balance', 'duration', 'y'], dtype='object')

In [ ]:
bank['education'].unique()

array(['tertiary', 'secondary', nan, 'primary'], dtype=object)

In [ ]:
df['temp']

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ... 
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [ ]:
bank['education']

0        tertiary
1       secondary
2       secondary
3       secondary
4       secondary
          ...    
7229    secondary
7230     tertiary
7231     tertiary
7232     tertiary
7233    secondary
Name: education, Length: 7234, dtype: object

In [ ]:
df[['date','temp']]

date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [ ]:
df.loc[:,['date','temp']]

date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [ ]:
df.iloc[:,[0,1]]

date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [ ]:
df[0:3]

date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9

In [ ]:
df.index=df['date']
df.loc['2010-08-01',['temp','mean_wind']]

temp         28.7
mean_wind     3.4
Name: 2010-08-01, dtype: object

In [ ]:
df.iloc[5]

date         2010-08-06
temp               26.8
max_wind            9.8
mean_wind           8.0
Name: 2010-08-06, dtype: object

In [ ]:
df.iloc[1:3,0:2]

date  temp
date                        
2010-08-02  2010-08-02  25.2
2010-08-03  2010-08-03  22.1

In [ ]:
w=df['temp']==df['temp'].max()
df[w]

date  temp  max_wind  mean_wind
1103  2013-08-08  31.3       7.8        4.6

In [ ]:
df[df['mean_wind'].isna()]

date  temp  max_wind  mean_wind
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
1694  2015-03-22  10.1      11.6        NaN
1704  2015-04-01   7.3      12.1        NaN
3182  2019-04-18  15.7      11.7        NaN

In [ ]:
df.isnull().sum() #결측 데이터 개수, 컬럼별 결측데이터 개수 확인

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

In [ ]:
df2=df.dropna()
df2.isnull().sum() #drop 후에 결과 확인

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

In [ ]:
dust=pd.read_excel('/content/drive/MyDrive/dust1.xlsx')
dust.head()

지역     망   측정소코드 측정소명        측정일시    SO2   CO     O3    NO2  PM10  \
0  서울 송파구  도시대기  111273  송파구  2021040101  0.004  1.0  0.002  0.066    50   
1  서울 송파구  도시대기  111273  송파구  2021040102  0.004  0.8  0.002  0.058    48   
2  서울 송파구  도시대기  111273  송파구  2021040103  0.004  0.8  0.002  0.055    44   
3  서울 송파구  도시대기  111273  송파구  2021040104  0.003  0.8  0.002  0.055    40   
4  서울 송파구  도시대기  111273  송파구  2021040105  0.004  0.8  0.002  0.053    38   

   PM25                주소  
0    18  서울 송파구 백제고분로 236  
1    20  서울 송파구 백제고분로 236  
2    20  서울 송파구 백제고분로 236  
3    20  서울 송파구 백제고분로 236  
4    17  서울 송파구 백제고분로 236

In [ ]:
dust=dust.drop(['지역','망','측정소코드'],axis=1)
dust.head()

측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236

In [ ]:
dust['city']='서울' #컬럼 생성
dust.head()

측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소  \
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236   
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236   
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236   
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236   
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236   

  city  
0   서울  
1   서울  
2   서울  
3   서울  
4   서울

In [ ]:
dust.rename(columns={'측정소명':'name',
                     '측정일시':'date',
                     '주소':'addr'}, inplace=True)
dust.columns

Index(['name', 'date', 'SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25', 'addr',
       'city'],
      dtype='object')

In [ ]:
dust.dtypes

name     object
date      int64
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr     object
city     object
dtype: object

In [ ]:
dust['date']=dust['date'].astype(str)
dust['date']=dust['date'].str.slice(0,8)
dust.dtypes

name     object
date     object
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr     object
city     object
dtype: object

In [ ]:
dust['date']=pd.to_datetime(dust['date'])
dust.dtypes

name            object
date    datetime64[ns]
SO2            float64
CO             float64
O3             float64
NO2            float64
PM10             int64
PM25             int64
addr            object
city            object
dtype: object

In [ ]:
dust['year']=dust['date'].dt.year
dust['month']=dust['date'].dt.month
dust['day']=dust['date'].dt.day
dust.head()

name       date    SO2   CO     O3    NO2  PM10  PM25              addr  \
0  송파구 2021-04-01  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236   
1  송파구 2021-04-01  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236   
2  송파구 2021-04-01  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236   
3  송파구 2021-04-01  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236   
4  송파구 2021-04-01  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236   

  city  year  month  day  
0   서울  2021      4    1  
1   서울  2021      4    1  
2   서울  2021      4    1  
3   서울  2021      4    1  
4   서울  2021      4    1

In [ ]:
s1=pd.read_excel('/content/drive/MyDrive/nation.xlsx')
s2=pd.read_excel('/content/drive/MyDrive/code.xlsx')

In [ ]:
pd.merge(s1,s2,on='국적코드')

국적코드  성별    입국객수    증가수  국적명
0  A01  남성  125000   8000  필리핀
1  A01  여성  130000  10000  필리핀
2  A05  남성     300     10   호주
3  A05  여성     200     50   호주
4  A06  남성  158912  24486  베트남
5  A06  여성  325000  63466  베트남

In [ ]:
s1.groupby('국적코드').sum()

성별    입국객수    증가수
국적코드                     
A01   남성여성  255000  18000
A05   남성여성     500     60
A06   남성여성  483912  87952

In [ ]:
s1.groupby(['국적코드','성별']).sum()

입국객수    증가수
국적코드 성별               
A01  남성  125000   8000
     여성  130000  10000
A05  남성     300     10
     여성     200     50
A06  남성  158912  24486
     여성  325000  63466

In [ ]:
temp=pd.read_excel('/content/drive/MyDrive/seoul.xlsx')
temp

\t\t지점번호  지점명         일시  평균기온(℃)  최고기온(℃)  \t최고기온시각  최저기온(℃) 최저기온시각일교차  \
0    \t\t108   서울 2002-01-01     -4.8      1.3  00:01:00     -7.5  23:44:00   
1    \t\t108   서울 2002-01-02     -9.9     -7.3  00:00:00    -11.4  08:32:00   
2    \t\t108   서울 2002-01-03     -6.5     -2.0  15:26:00    -12.0  05:54:00   
3    \t\t108   서울 2002-01-04      1.5      5.7  14:28:00     -3.4  00:33:00   
4    \t\t108   서울 2002-01-05     -0.7      1.9  15:41:00     -3.0  23:38:00   
..       ...  ...        ...      ...      ...       ...      ...       ...   
368       \t  NaN        NaT      NaN      NaN       NaN      NaN       NaN   
369       \t  NaN        NaT      NaN      NaN       NaN      NaN       NaN   
370     \t\t  NaN        NaT      NaN      NaN       NaN      NaN       NaN   
371       \t  NaN        NaT      NaN      NaN       NaN      NaN       NaN   
372       \t  NaN        NaT      NaN      NaN       NaN      NaN       NaN   

     Unnamed: 8  
0           8.8  
1           4.1  
2          10.0  
3           9.1  
4           4.9  
..          ...  
368         NaN  
369         NaN  
370         NaN  
371         NaN  
372         NaN  

[373 rows x 9 columns]

In [ ]:
temp.dtypes

\t\t지점번호              object
지점명                   object
일시            datetime64[ns]
평균기온(℃)              float64
최고기온(℃)              float64
\t최고기온시각              object
최저기온(℃)              float64
최저기온시각일교차             object
Unnamed: 8           float64
dtype: object

In [ ]:
temp.columns

Index(['지점명', '일시', '평균기온(℃)', '최고기온(℃)', '\t최고기온시각', '최저기온(℃)', '최저기온시각일교차',
       'Unnamed: 8'],
      dtype='object')

In [ ]:
temp = temp.drop(index=range(365, 373))
temp

지점명         일시  평균기온(℃)  최고기온(℃)  \t최고기온시각  최저기온(℃) 최저기온시각일교차  Unnamed: 8
0    서울 2002-01-01     -4.8      1.3  00:01:00     -7.5  23:44:00         8.8
1    서울 2002-01-02     -9.9     -7.3  00:00:00    -11.4  08:32:00         4.1
2    서울 2002-01-03     -6.5     -2.0  15:26:00    -12.0  05:54:00        10.0
3    서울 2002-01-04      1.5      5.7  14:28:00     -3.4  00:33:00         9.1
4    서울 2002-01-05     -0.7      1.9  15:41:00     -3.0  23:38:00         4.9
..   ..        ...      ...      ...       ...      ...       ...         ...
360  서울 2002-12-27     -4.5     -0.1  15:42:00     -8.0  07:41:00         7.9
361  서울 2002-12-28     -0.9      3.2  13:19:00     -5.5  01:53:00         8.7
362  서울 2002-12-29     -2.4      1.7  14:51:00     -5.8  08:12:00         7.5
363  서울 2002-12-30     -2.0      1.6  15:24:00     -6.3  05:45:00         7.9
364  서울 2002-12-31     -1.4      1.9  15:13:00     -3.7  23:46:00         5.6

[365 rows x 8 columns]

In [ ]:
temp=temp.rename(columns={'Unnamed: 8':'일교차'})
temp

지점명         일시  평균기온(℃)  최고기온(℃)  \t최고기온시각  최저기온(℃) 최저기온시각일교차   일교차
0    서울 2002-01-01     -4.8      1.3  00:01:00     -7.5  23:44:00   8.8
1    서울 2002-01-02     -9.9     -7.3  00:00:00    -11.4  08:32:00   4.1
2    서울 2002-01-03     -6.5     -2.0  15:26:00    -12.0  05:54:00  10.0
3    서울 2002-01-04      1.5      5.7  14:28:00     -3.4  00:33:00   9.1
4    서울 2002-01-05     -0.7      1.9  15:41:00     -3.0  23:38:00   4.9
..   ..        ...      ...      ...       ...      ...       ...   ...
360  서울 2002-12-27     -4.5     -0.1  15:42:00     -8.0  07:41:00   7.9
361  서울 2002-12-28     -0.9      3.2  13:19:00     -5.5  01:53:00   8.7
362  서울 2002-12-29     -2.4      1.7  14:51:00     -5.8  08:12:00   7.5
363  서울 2002-12-30     -2.0      1.6  15:24:00     -6.3  05:45:00   7.9
364  서울 2002-12-31     -1.4      1.9  15:13:00     -3.7  23:46:00   5.6

[365 rows x 8 columns]

In [ ]:
temp=temp.drop(['\t최고기온시각','최저기온시각일교차'],axis=1)
temp

지점명         일시  평균기온(℃)  최고기온(℃)  최저기온(℃)   일교차
0    서울 2002-01-01     -4.8      1.3     -7.5   8.8
1    서울 2002-01-02     -9.9     -7.3    -11.4   4.1
2    서울 2002-01-03     -6.5     -2.0    -12.0  10.0
3    서울 2002-01-04      1.5      5.7     -3.4   9.1
4    서울 2002-01-05     -0.7      1.9     -3.0   4.9
..   ..        ...      ...      ...      ...   ...
360  서울 2002-12-27     -4.5     -0.1     -8.0   7.9
361  서울 2002-12-28     -0.9      3.2     -5.5   8.7
362  서울 2002-12-29     -2.4      1.7     -5.8   7.5
363  서울 2002-12-30     -2.0      1.6     -6.3   7.9
364  서울 2002-12-31     -1.4      1.9     -3.7   5.6

[365 rows x 6 columns]

In [ ]:
temp.columns

Index(['지점명', '일시', '평균기온(℃)', '최고기온(℃)', '최저기온(℃)', '일교차'], dtype='object')

In [ ]:
day=temp[['일시','최고기온(℃)', '최저기온(℃)']]
day.iloc[58:59]

일시  최고기온(℃)  최저기온(℃)
58 2002-02-28     11.3      2.9

In [ ]:
temp.index=temp['일시']
temp.loc['2002-02-28',['최고기온(℃)', '최저기온(℃)']]

최고기온(℃)    11.3
최저기온(℃)     2.9
Name: 2002-02-28 00:00:00, dtype: object

In [ ]:
avg_temp=temp[temp['평균기온(℃)']>=20]
avg_temp

지점명         일시  평균기온(℃)  최고기온(℃)  최저기온(℃)   일교차
일시                                                        
2002-04-22  서울 2002-04-22     21.0     27.7     12.9  14.8
2002-05-14  서울 2002-05-14     21.3     25.6     15.4  10.2
2002-05-22  서울 2002-05-22     20.0     26.0     15.8  10.2
2002-05-23  서울 2002-05-23     21.9     27.7     15.6  12.1
2002-05-29  서울 2002-05-29     20.6     27.0     13.8  13.2
...         ..        ...      ...      ...      ...   ...
2002-09-24  서울 2002-09-24     20.3     26.4     14.7  11.7
2002-09-25  서울 2002-09-25     20.9     26.8     15.2  11.6
2002-09-26  서울 2002-09-26     21.6     26.3     17.4   8.9
2002-09-27  서울 2002-09-27     20.5     24.8     17.5   7.3
2002-09-28  서울 2002-09-28     20.6     26.0     16.5   9.5

[113 rows x 6 columns]

In [ ]:
w=temp['평균기온(℃)']==temp['평균기온(℃)'].max()
result=temp[w]
max_temp=result.iloc[:,1:5]
max_temp

일시  평균기온(℃)  최고기온(℃)  최저기온(℃)
일시                                              
2002-07-28 2002-07-28     30.4     34.8     25.6

In [ ]:
covid=pd.read_csv('/content/drive/MyDrive/covid.csv',encoding='cp949')
covid

항목  사례수    증가    감소  변화없음
0    스마트폰  999  78.9   1.7  19.4
1    텔레비전  965  68.5   3.9  27.6
2  개인용 PC  973  65.7   3.7  30.6
3  태블릿 PC  662  46.8   4.2  49.0
4     라디오  687  35.5  12.5  52.0
5    잡지·책  776  31.3  17.8  50.9
6    종이신문  552  17.6  23.2  59.2

In [ ]:
max=covid['사례수']==covid['사례수'].max()
covid[max]

항목  사례수    증가   감소  변화없음
0  스마트폰  999  78.9  1.7  19.4

In [ ]:
covid.sort_values(by='증가', ascending=False)
covid.head(3)

항목  사례수    증가   감소  변화없음
0    스마트폰  999  78.9  1.7  19.4
1    텔레비전  965  68.5  3.9  27.6
2  개인용 PC  973  65.7  3.7  30.6

In [3]:
vaccine=pd.read_csv('/content/drive/MyDrive/vaccine.csv')
vaccine.tail(5)

date  subject  day1num  day1sum  day1rate  day2num  day2sum  \
174  2021.04.25  1023346    23323   350631      34.2     3411    18513   
175  2021.04.24  1023346      200   350427      34.2        0    18513   
176  2021.04.23  1027740    10195   345764      33.6      119    18376   
177  2021.04.22  1023538    27074   317386      31.0     2479    15901   
178  2021.04.21  1019322    22501   291857      28.6     2358    13543   

     day2rate  
174       1.8  
175       1.8  
176       1.8  
177       1.6  
178       1.3

In [ ]:
vaccine.columns

Index(['date', 'subject', 'day1num', 'day1sum', 'day1rate', 'day2num',
       'day2sum', 'day2rate'],
      dtype='object')

In [8]:
vaccine=vaccine.drop(['day1sum', 'day1rate','day2sum', 'day2rate'],axis=1)
vaccine

date  subject  day1num  day2num
0    2021.10.16  9505868    10673    66910
1    2021.10.15  9505868    14556   133580
2    2021.10.14  9505868     9609    94569
3    2021.10.13  9505868     9804    77503
4    2021.10.12  9505868    17274   110204
..          ...      ...      ...      ...
174  2021.04.25  1023346    23323     3411
175  2021.04.24  1023346      200        0
176  2021.04.23  1027740    10195      119
177  2021.04.22  1023538    27074     2479
178  2021.04.21  1019322    22501     2358

[179 rows x 4 columns]

In [1]:
import pandas as pd
import numpy as np


In [9]:
vaccine.describe()

subject        day1num        day2num
count  1.790000e+02     179.000000     179.000000
mean   5.086644e+06   40078.150838   34096.636872
std    3.324235e+06   44231.469656   40745.688278
min    1.019322e+06       0.000000       0.000000
25%    2.279241e+06    4385.000000    4794.500000
50%    3.943320e+06   23323.000000   16581.000000
75%    9.505868e+06   71634.500000   50950.000000
max    9.795426e+06  169036.000000  200186.000000

In [21]:
vaccine=pd.read_csv('/content/drive/MyDrive/vaccine.csv')
vaccine['date'] = pd.to_datetime(vaccine['date'], format='%Y.%m.%d')
vaccine['month'] = vaccine['date'].dt.month
vaccine=vaccine.drop(['date'],axis=1)
vaccine.groupby('month').mean()

subject       day1num       day1sum   day1rate       day2num  \
month                                                                      
4      1.054686e+06  22060.100000  3.860085e+05  36.440000   2304.600000   
5      1.289918e+06  18225.548387  6.451063e+05  51.435484   9734.000000   
6      3.167106e+06  55957.200000  2.234760e+06  69.240000  20147.300000   
7      3.819340e+06  25807.870968  3.064527e+06  80.232258   9934.903226   
8      6.702049e+06  57667.258065  4.430462e+06  72.509677  55575.000000   
9      9.556825e+06  65715.000000  6.466827e+06  67.620000  62162.000000   
10     9.505868e+06   9406.312500  7.486763e+06  78.762500  79900.750000   

            day2sum   day2rate  
month                           
4      2.276060e+04   2.140000  
5      1.661513e+05  12.529032  
6      6.229332e+05  19.276667  
7      1.167138e+06  30.467742  
8      1.984530e+06  31.080645  
9      3.887544e+06  40.663333  
10     5.541498e+06  58.343750

In [15]:
vaccine.dtypes

date       object
subject     int64
day1num     int64
day2num     int64
dtype: object

In [25]:
su = pd.read_csv('/content/drive/MyDrive/signup.csv', encoding='cp949')
prof = pd.read_csv('/content/drive/MyDrive/professor.csv', encoding='cp949')
prof

담당교수     학과
0  양숙희  컴퓨터공학
1  장은실   정보통신
2  오경선   인공지능
3  황복동  컴퓨터공학
4  정명식   인공지능

In [30]:
prof['학과'].value_counts()

학과
컴퓨터공학    2
인공지능     2
정보통신     1
Name: count, dtype: int64

In [26]:
su

수강코드    과목명 담당교수
0   111    파이썬  양숙희
1   222  데이터분석  오경선
2   333   인공지능  장은실
3   444   선형대수  황복동
4   555   이산수학  정명식
5   666  컴퓨터개론  최봉수
6   777   자료구조  김진영
7   888   정보통신  김진호

In [27]:
pd.merge(su,prof,on='담당교수')

수강코드    과목명 담당교수     학과
0   111    파이썬  양숙희  컴퓨터공학
1   222  데이터분석  오경선   인공지능
2   333   인공지능  장은실   정보통신
3   444   선형대수  황복동  컴퓨터공학
4   555   이산수학  정명식   인공지능